### PR TITLE
fix(resize): validate lv size before executing lvextend

### LINKED ISSUE #381: openebs-lvm-plugin fails unnecessary resize
**What steps did you take and what happened:**

PVC size is increased. PVC is stuck in resize state. The openebs-lvm-plugin seems to run an unnecessary LVM resize, which fails because the size wasn't changed:

```
GRPC call: /csi.v1.Node/NodeExpandVolume requests {"capacity_range":{"required_bytes":1100585369600},"staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/local.csi.openebs.io/25299795ba8380ae5e9f77a6d17887cefd205818e9766e5eae0940156cc58862/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_id":"pvc-76e8cd33-4142-4c7a-893a-43f8c6013a96","volume_path":"/var/lib/kubelet/pods/bbc0a48c-8b0b-4ada-ae9a-1bbe9778a6ae/volumes/kubernetes.io~csi/pvc-76e8cd33-4142-4c7a-893a-43f8c6013a96/mount"}
lvm_util.go:279] lvm: said into stderr:   No size change.
lvm_util.go:431] lvm: could not resize the volume storage/pvc-76e8cd33-4142-4c7a-893a-43f8c6013a96 cmd [/dev/storage/pvc-76e8cd33-4142-4c7a-893a-43f8c6013a96 -L 1100585369600b -r] error:   New size (262400 extents) matches existing size (262400 extents).
```

**What did you expect to happen:**

Resize was successful.

**Environment:**

- LVM Driver version - 1.6.1 / 1.7.0-development / latest - same result
- Kubernetes version (use `kubectl version`): 1.28.2
- Kubernetes installer & version: kubeadm ?
- Cloud provider or hardware configuration: Bare metal x86_64 cluster with SSDs/HDDs
- OS (e.g. from `/etc/os-release`): Debian GNU/Linux 12 (bookworm)

### PR DESCRIPTION
**Pull request by dsharma-dc**
Fetch the lv size in extents and validate if we really need to run the lvextend.

**Why is this PR required? What issue does it fix?**:
Fixes #381

**What this PR does?**:
Fetch the lv size in extents and validate if we really need to run the lvextend.

**Does this PR require any upgrade changes?**:
No

**If the changes in this PR are manually verified, list down the scenarios covered:**:
Do lvextend of LV on the host. Then edit the PVC to request the same size as already done via lvextend.

**Any additional information for your reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [x] Fixes #381
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Has the change log section been updated?
- [ ] Commit has unit tests
- [ ] Commit has integration tests
- [ ] (Optional) Are upgrade changes included in this PR? If not, mention the issue/PR to track:
- [ ] (Optional) If documentation changes are required, which issue on https://github.com/openebs/openebs-docs is used to track them:

### CODE REVIEW

File: pkg/lvm/lvm_util.go [hunk 1]
```diff
@@ -375,6 +375,55 @@ func GetVolumeDevPath(vol *apis.LVMVolume) (string, error) {
...
+	if err != nil {
+		klog.Warningf("failed to parse VG extent size '%s' to integer: %w", vgExtentSizeStr, err)
+		return true
+	}
+
+	// 3. Calculate current Logical Extents
+	// Ensure VG extent size is not zero to prevent division by zero.
+	if vgExtentSize == 0 {
+		klog.Warningf("VG extent size is zero, cannot calculate logical extents")
+		return true
```
Comment (Abhinandan-Purkait) [inline pkg/lvm/lvm_util.go:417]: So is this safe to allow resize in this case?

**Review by Abhinandan-Purkait — APPROVED** [review]

File: pkg/lvm/lvm_util.go (hunk 1 above)
Comment (dsharma-dc) [reply pkg/lvm/lvm_util.go:417]: > So is this safe to allow resize in this case?

In this case we'll go ahead and attempt resize, and fail with error as we do today. Assuming this was temporary, the subsequent attempts(of NodeExpandVolume) will pass and the error flood will stop.

File: pkg/lvm/lvm_util.go [hunk 2]
```diff
@@ -375,6 +375,55 @@ func GetVolumeDevPath(vol *apis.LVMVolume) (string, error) {
 	return dev, nil
 }
 
+// Validate the size volume based on extents. If the number of extents are already
+// greater than or equal to required, then make a no-op.
+func validateLVExtentSizes(vol *apis.LVMVolume, desiredSizeBytes uint64) bool {
```
Comment (tiagolobocastro) [inline pkg/lvm/lvm_util.go]: function name is a bit confusing on what it is doing especially as it's returning true in case of errors
maybe something more like: `needsLvResize` ?

File: pkg/lvm/lvm_util.go [hunk 3]
```diff
@@ -375,6 +375,55 @@ func GetVolumeDevPath(vol *apis.LVMVolume) (string, error) {
...
+	if vgExtentSize == 0 {
+		klog.Warningf("VG extent size is zero, cannot calculate logical extents")
+		return true
+	}
+
+	currNumLEs := uint64(lvSize / vgExtentSize)
+	requiredNumLEs := uint64(desiredSizeBytes / vgExtentSize)
+	klog.Infof("num logical extents - current: %v, required:  %v", currNumLEs, requiredNumLEs)
+
+	return currNumLEs < requiredNumLEs
```
Comment (tiagolobocastro) [inline pkg/lvm/lvm_util.go:424]: Is the `LvSize` always multiple of `vgExtentSize`?

Comment (dsharma-dc) [reply pkg/lvm/lvm_util.go:424]: > Is the `LvSize` always multiple of `vgExtentSize`?

Yes, by design of lvm apparently. Similar to blobs being multiple of blobstore cluster size.

File: pkg/lvm/lvm_util.go (hunk 2 above)
Comment (dsharma-dc) [reply pkg/lvm/lvm_util.go]: > function name is a bit confusing on what it is doing especially as it's returning true in case of errors maybe something more like: `needsLvResize` ?

renamed to `needsLvResize`

**Review by tiagolobocastro — APPROVED** [review]

**Review by abhilashshetty04 — APPROVED** [review]
